spring.application.name=modulobase

# JPA specific configs
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@ol8-19.localdomain:1521:orcl
#spring.datasource.url=jdbc:oracle:thin:@micrium2:1521:orcl
spring.datasource.username=MOD_BASE
spring.datasource.password=MOD_BASE
# Puede ser update, validate, create-drop
spring.jpa.hibernate.ddl-auto=none          
# Muestra las consultas SQL en consola
spring.jpa.show-sql=false
# No es necesario especificar el dialecto de Oracle, Hibernate lo detectar\u00c3\u00a1 automaticamente
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect 
spring.jpa.open-in-view=true


# Validar Propiedades HikariCP Configuration
spring.datasource.hikari.driver-class-name = oracle.jdbc.OracleDriver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.connection-test-query = SELECT 1 FROM DUAL
spring.datasource.hikari.connection-timeout = 30000
spring.datasource.hikari.idle-timeout = 60000
spring.datasource.hikari.max-lifetime = 1800000
#grupo puede alcanzar, incluidas las conexiones 
spring.datasource.hikari.maximum-pool-size = 20
#conexiones inactivas que HikariCP intenta mantener en el grupo.
spring.datasource.hikari.minimum-idle = 5
spring.datasource.hikari.validation-timeout = 5000

spring.client.url=*

server.forward-headers-strategy=NATIVE
spring.jpa.properties.hibernate.format_sql=true
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

# l\u00c3\u00admites de tasas de solicitudes de Bucket4j
bucket4j.limit=50
bucket4j.duration.minutes=1

#codigo generado aleateario para ala generacion de token
jwt.secret=alepacomatonalepacomatonalepacomatonalepacomatonalepacomatonalepacomatonalepacomatonalepacomatonalepacomatonalepacomatonalepacomatonalepacomatonalepacomaton
#tiempo de valides de los token, en horas
jwt.timelife=24

# Servidor (Tomcat, Jetty, Undertow)
#server.port=8081
server.servlet.context-path=/modulobase/api/v1
#spring.security.content-security-policy=default-src 'self'; connect-src 'self' ws://127.0.0.1:8085
